language: php
php:
  - '7.0'
  - nightly
  - hhvm
  - '5.6'

before_script:
  - composer update --dev
script:
  - phpunit --bootstrap lib/danog/PHP/Struct.php tests/danog/PHP/StructTest.php --verbose
