language: php
php:
  - '7.0'
  - nightly
  - hhvm
  - '5.6'

before_script:
  - composer update --dev
script:
  - vendor/phpunit/phpunit/phpunit --bootstrap lib/danog/PHP/Struct.php --bootstrap lib/danog/PHP/StructException.php tests/danog/PHP/StructClass.php --bootstrap lib/danog/PHP/StructTools.php tests/danog/PHP/StructTest.php --verbose
