language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

script:
  - phpunit --bootstrap lib/danog/PHP/StructException.php --bootstrap lib/danog/PHP/Struct.php tests/danog/PHP/StructTest.php --verbose
