sudo: required
dist: trusty
group: edge
language: php
php:
  - '7.0'
  - nightly
  - hhvm
  - '5.6'
addons:
  apt:
    packages:
    - python3

before_script:
  - composer update --dev
script:
  - vendor/phpunit/phpunit/phpunit --bootstrap lib/danog/PHP/Struct.php --bootstrap lib/danog/PHP/StructException.php tests/danog/PHP/StructClass.php --bootstrap lib/danog/PHP/StructTools.php tests/danog/PHP/StructTest.php --verbose
  - tests/danog/PHP/py2php.php
  - tests/danog/PHP/php2py.py
