language: php
php:
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer update --dev
script:
  - vendor/phpunit/phpunit/phpunit --bootstrap lib/danog/PHP/Struct.php tests/danog/PHP/StructTest.php --verbose
